export const TEXTS = {
  SEND: 'Enviar',
  NAME: 'Nombre',
  LASTNAME: 'Apellido',
  EMAIL: 'Correo',
  PHONENUM: 'Telefono',
  PHONETYPE: 'Tipo Telefono',
  MESSAGE: 'Mensaje',
  NAME_PLACEHOLDER: 'Escribe tu nombre',
  EMAIL_PLACEHOLDER: 'Escribe tu correo',
  MESSAGE_PLACEHOLDER: 'Escribe tu mensaje',
  REQUIRED_FORM: 'Campo requerido',
  EMAIL_INVALID: 'El correo no es válido',
  HOME: 'Inicio',
  ABOUT: 'Sobre mí',
  PROJECTS: 'Proyectos',
  CONTACT: 'Contacto',
  HEADER: 'Noé Dev',
  MINLENGTH_FORM: 'Mínimo 3 caracteres',
  MAXLENGTH_FORM: 'Máximo 100 caracteres',
  ERROR: 'Error',
  SUCCESS: 'Éxito',
  FORM_SUBMITTED: 'Formulario enviado correctamente',
  FORM_ERROR: 'Error al enviar el formulario',
};
